name: Build on every push except main branch

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v3
      - name: Get changed files in the frontend
        id: frontend-changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            waltid-applications/waltid-web-portal/**
            waltid-applications/waltid-web-wallet/web/**
      - name: Update gradle.properties for iOS build
        if: ${{ matrix.os == 'macos-latest' }}
        run: sed -i '' 's/^enableIosBuild=false/enableIosBuild=true/' gradle.properties
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v3
        with:
          arguments: build --no-daemon
        if: ${{ steps.frontend-changed-files.outputs.any_changed == 'false' }}
