name: Build on every push except main branch

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      artifact: true
  ebsi-ct-v3:
    uses: walt-id/waltid-identity/.github/workflows/ebsictv3.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    needs: [ version, docker ]
    secrets: inherit
    with:
      artifact: issuer-api
      tag: "waltid/issuer-api:${{ needs.version.outputs.release_version }}"