name: Release on manual push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      tag: latest
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      deployment: prod
      namespace: default
      portals: portals
      kubeconfig_secret: NL_KUBE_CONFIG
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  release:
    uses: walt-id/waltid-identity/.github/workflows/changelog.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: [ tag ]
    with:
      tag: ${{ needs.tag.outputs.tag }}