name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}s
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    secrets: inherit
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@a89c22088e7a1f397ed4c24e35554023c27f5c6e
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}